Moving Space Travelers' Hub From dev to main
r-ahmed2022/spacetravellerhub-app pull request #37
Opened 2023-02-01 18:30 UTC by shegy28

**We developed a Space Travelers' Hub App based on data from Space X's API. The Space Travelers' Hub App displays a list of available rockets on its homepage and a list of missions on its mission page. Both lists options can be booked and reserved, and the reserved rocket or mission shows on the profile page.**

**Config & basic setup**

- Created the React App.
- Installed [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).
- Downloaded the [free image](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style) for the app logo.
- Created routes and view components for Rockets, Missions and My Profile.
- Used `<NavLink />` for the page navigation links and style active class to indicate which section/page user is currently on (underline active navigation link).
- Create directories for all Redux state slice files.

**Redux: Fetch data and update Redux store**
Upon first render  we fetched data from the SpaceX API endpoints:

> Rockets: https://api.spacexdata.com/v4/rockets
> Missions: https://api.spacexdata.com/v3/missions

Once the data are fetched, We dispatched an action to store the selected data in Redux store:

- [ ]  **Rockets:**

> id
> rocket_name
> description
> flickr_images

- [ ] **Missions:**

> mission_id
> mission_name
> description

**Render UI:lists**

- Used useSelector() Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes.
- **Redux**: Wrote actions and reducers for booking rockets and joining missions
- When a user clicks the "Reserve rocket" button or "Join mission" button, an action is dispatched to update the store. 

- Create a reducers and action dispatcher for the "Join Mission" or "Reserve rocket"  button that changes the to reserved: true. 
- **Redux:** Wrote actions and reducers for canceling rockets and leaving missions

Dispatch these actions upon click on the corresponding buttons.

**Render UI: My Profile section**

- Composed two layout and list ONLY the rockets reserved and missions joined by the user (as per design):
- Render a list of all joined missions.
- Render a list of all reserved rockets.

2023-02-01 19:53 UTC, Owusu-Desmond requested changes
Hi @shegy28 and @r-ahmed2022 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Q1r6trHMbDtGaUpofD/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set of of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅
📌 Nice UI design ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 19:53 UTC, Owusu-Desmond commented on README.md
> +
- [ ] Please replace `Author1` with your name to help people who visit the repo know the collaborators' names. :smile:

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/redux/Missions/mission.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code.

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/components/EachMission.js
> +/* eslint-disable react/prop-types */
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code. :pray:

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/components/MissionList.js
> +const MissionList = (props) => {
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code. :pray:

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/pages/Profile.js
> +import React from 'react';
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code. :pray:

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/redux/Rockets/rocket.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code. :pray:

2023-02-01 19:53 UTC, Owusu-Desmond commented on src/testing/component.test.js
> +import React from 'react';
- [ ] Please make sure that you do not disable any `eslint` error since it is helping to write clean code. :pray:

2023-02-01 19:53 UTC, Owusu-Desmond commented on README.md
> +
- [ ] Why is it that, you already have the `rocket page`, `mission page`, and `profile page` but you are still stating them as future features :smile:

2023-02-02 07:49 UTC, shegy28 commented on README.md
> +
done as advised

2023-02-02 07:53 UTC, shegy28 commented on src/testing/component.test.js
> +import React from 'react';
done as advised

2023-02-02 07:54 UTC, shegy28 commented on src/components/MissionList.js
> +const MissionList = (props) => {
done advised

2023-02-02 07:57 UTC, shegy28 commented on src/pages/Profile.js
> +import React from 'react';
done as advised

2023-02-02 08:04 UTC, shegy28 commented on README.md
> +
done as advised

2023-02-02 08:04 UTC, shegy28 commented on src/redux/Rockets/rocket.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
done as advised

2023-02-02 08:04 UTC, shegy28 commented on src/components/EachMission.js
> +/* eslint-disable react/prop-types */
done as advised

2023-02-02 08:05 UTC, shegy28 commented on src/redux/Missions/mission.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
done as advised

2023-02-02 08:21 UTC, ghost approved these changes
Hi Team , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ README is okay
✅ App is works as expected 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 08:23 UTC, merged